name: Bug Report
about: For reporting problems
title: Let us know what the problem is!
issue_body: true
assignees: labrose
inputs:
- type: dropdown
  attributes:
    label: Operating System
    required: true
    choices:
      - Windows 10
      - iOS
      - Linux
      - Android
      - Mac OS
- type: checkboxes
  attributes:
    label: Code of Conduct
    choices:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
      required: true


